"""модели ядра

Revision ID: 45175cfb9283
Revises: 
Create Date: 2026-07-05 05:24:07.741696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45175cfb9283'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='user', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone'))
    )
    op.create_table('bundles',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sort', sa.Integer(), server_default='0', nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bundles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bundles'))
    )
    op.create_index(op.f('ix_bundles_user_id'), 'bundles', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('pdf_key', sa.String(length=500), nullable=True),
    sa.Column('public_uuid', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'sent', 'approved')", name=op.f('ck_documents_status_valid')),
    sa.CheckConstraint("type IN ('estimate', 'contract', 'act')", name=op.f('ck_documents_type_valid')),
    sa.ForeignKeyConstraint(['parent_id'], ['documents.id'], name=op.f('fk_documents_parent_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_documents_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('public_uuid', name=op.f('uq_documents_public_uuid'))
    )
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('parse_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=False),
    sa.Column('parsed_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('corrected_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_parse_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parse_logs'))
    )
    op.create_index(op.f('ix_parse_logs_user_id'), 'parse_logs', ['user_id'], unique=False)
    op.create_table('price_items',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('niche', sa.String(length=20), server_default='hvac', nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('synonyms', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sort', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_price_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_items'))
    )
    op.create_index(op.f('ix_price_items_user_id'), 'price_items', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('brand_name', sa.String(length=200), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('requisites', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('logo_key', sa.String(length=500), nullable=True),
    sa.Column('signature_key', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_profiles'))
    )
    op.create_table('subscriptions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('plan', sa.String(length=20), server_default='free', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('yookassa_payment_method_id', sa.String(length=100), nullable=True),
    sa.CheckConstraint("plan IN ('free', 'pro', 'business')", name=op.f('ck_subscriptions_plan_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_subscriptions'))
    )
    op.create_table('usage_counters',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('documents_created', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_usage_counters_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'month', name=op.f('pk_usage_counters'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_counters')
    op.drop_table('subscriptions')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_price_items_user_id'), table_name='price_items')
    op.drop_table('price_items')
    op.drop_index(op.f('ix_parse_logs_user_id'), table_name='parse_logs')
    op.drop_table('parse_logs')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_bundles_user_id'), table_name='bundles')
    op.drop_table('bundles')
    op.drop_table('users')
    # ### end Alembic commands ###
