"""profile theme

Revision ID: e512b5262552
Revises: 5b9c07ac95d2
Create Date: 2026-07-14 12:30:50.816042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e512b5262552'
down_revision: Union[str, None] = '5b9c07ac95d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('theme', sa.String(length=10), server_default='system', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'theme')
    # ### end Alembic commands ###
